### ISSUE TITLE
Accessibility Request - Website Text Color

### ISSUE THREAD

**Issue by ServiceDog** [Arrow-air/website#6]
The text color on the front page is fairly close the background color in several of the lower sections:

![image](https://user-images.githubusercontent.com/6334638/153792885-738a46d8-ee5b-4c24-b68e-37477fb60c18.png)

Would recommend moving to a color nearer to white for better contrast with this background

**Comment by GoodluckH** [comment]
The home page of our website had undergone major UI changes. Better font colors were applied to contrast with the background.
